/* ------------------------------------------------------------------
   Writes the pages that are the same in every language but its words:

   - the home page, src/content/docs/<lang>/index.mdx (English at the
     root), whose body is src/components/Home.astro;
   - a placeholder for every article in the menu that is not written
     yet, so the menu leads somewhere in every language. The placeholder
     says, in the reader's language, that the article is on its way.

   A file written by this script carries GENERATED in its first lines and
   is rewritten on every run. A file without it is somebody's work and is
   never touched — so writing an article is simply replacing its
   placeholder. Once the English article exists, the other languages
   show it (with Starlight's "not translated yet" note) until their own
   translation is added, so no placeholders are written for them.

       npm run gen:pages
   ------------------------------------------------------------------ */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { languages } from '../src/i18n/languages.mjs';
import { sidebar } from '../src/i18n/sidebar.mjs';

const DOCS = new URL('../src/content/docs/', import.meta.url);
const MARK = 'GENERATED by scripts/gen-pages.mjs';
const read = async (p) => JSON.parse(await readFile(new URL(p, import.meta.url), 'utf8'));
const plain = (html) => html.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
// a JSON string is a valid YAML scalar, and escapes whatever needs it
const y = (s) => JSON.stringify(s);

const folder = (dir) => (dir === 'root' ? DOCS : new URL(`${dir}/`, DOCS));
const components = (depth) => `${'../'.repeat(depth + 2)}components`;

/** 'mine' — written by this script; 'theirs' — written by hand; null — absent */
async function owner(url) {
  try {
    return (await readFile(url, 'utf8')).includes(MARK) ? 'mine' : 'theirs';
  } catch {
    return null;
  }
}

async function write(url, text) {
  if ((await owner(url)) === 'theirs') return false;
  await mkdir(new URL('./', url), { recursive: true });
  await writeFile(url, text);
  return true;
}

let written = 0;
const articles = sidebar.flatMap((group) => group.items);

for (const { code, dir } of languages) {
  const s = await read(`../src/data/site/${code}.json`);
  const d = await read(`../src/content/i18n/${code}.json`);
  const depth = dir === 'root' ? 0 : 1;

  const home = `---
# ${MARK} — edit the script or the catalogues, not this file.
title: ${y(d['docs.home.title'])}
description: ${y(plain(s['meta.description']))}
---

import Home from '${components(depth)}/Home.astro';

<Home lang=${y(code)} />
`;
  if (await write(new URL('index.mdx', folder(dir)), home)) written++;

  for (const { slug, label, translations } of articles) {
    const english = await owner(new URL(`${slug}.mdx`, DOCS));
    if (dir !== 'root' && english === 'theirs') continue; // falls back to the English article
    const title = translations?.[code] ?? label;
    const stub = `---
# ${MARK} — replace this file with the article.
title: ${y(title)}
---

import Soon from '${components(depth + slug.split('/').length - 1)}/Soon.astro';

<Soon />
`;
    if (await write(new URL(`${slug}.mdx`, folder(dir)), stub)) written++;
  }
}
console.log(`${written} pages written`);
